# Generated by Django 5.0.1 on 2024-02-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyDataManager', '0009_bookpublication_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='college_level',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department_level',
            field=models.CharField(default='', max_length=255),
        ),
    ]
